### ISSUE TITLE
Unreal project won't start at Unreal 5.1.1 

### ISSUE THREAD

**Issue by ivanvodoleev** [audiokinetic/Gyms#1]
Startup error

The following modules are missing or built with a different engine version:
Gyms
GymEditorUtilities
GamepadUUMGPlugin

Would you like to rebuild them now?

**Comment by ak-mdonais** [comment]
The Gyms are not pre-built (especially not at that repository size), they need to be built using your platform's compiler. Please follow [Wwise Integrations for Unreal documentation](https://www.audiokinetic.com/en/library/edge/?source=UE4&id=index.html) on how to integrate a Wwise version from the Wwise Launcher, and then compile the project.

For reference, due to Unreal restrictions on C++-based plug-ins, they cannot be integrated as a Blueprint project. Unreal projects integrating Wwise must be compiled.
